### ISSUE TITLE
NPE on auto-test done by Google

### ISSUE THREAD

**Issue by CyrilleGuimezanes** [Wizcorp/cordova-plugin-wizpurchase#48]
Hello,

When I publish my app, Google starts auto-test on various devices. Since two releases Google give a NPE with this stack trace:

```
java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getBuyIntent(int, java.lang.String, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
 	at com.smartmobilesoftware.util.IabHelper.launchPurchaseFlow(IabHelper.java:386)
 	at com.smartmobilesoftware.util.IabHelper.launchPurchaseFlow(IabHelper.java:338)
 	at jp.wizcorp.wizpurchase.WizPurchase.buy(WizPurchase.java:416)
 	at jp.wizcorp.wizpurchase.WizPurchase.access$200(WizPurchase.java:40)
 	at jp.wizcorp.wizpurchase.WizPurchase$4.run(WizPurchase.java:296)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 	at java.lang.Thread.run(Thread.java:818)

```

In a physical use, no exception...

Google told me that the tested device is Galaxy S6 under Android 5.1. Others 5.1 devices pass all the tests.

**Comment by jrouault** [comment]
Thanks for pointing out this issue. 👍 

I'll try to have a look at this this week.

**Comment by jrouault** [comment]
@CyrilleGuimezanes By the way, do you have any JS code to share that could help reproduce/understand this issue?

**Comment by CyrilleGuimezanes** [comment]
Actually it's a really simple use of your plugin and in a normal use (when I use my phone under android 6.0), it not crash

Here is the logcat attached to Google bug report if that can help:
[logcat.txt](https://github.com/Wizcorp/cordova-plugin-wizpurchase/files/714095/logcat.txt)

**Comment by jrouault** [comment]
Hello,
Thanks for the logcat file! I tried to trace back your error but I couldn't find why you have this exception as everything seems to be properly initialized.
As I have no way to reproduce it currently, would you be able to make a new build with debug logs activated in `IabHelper` and attach the resulting logs?
This can be done either by:
- directly replacing `IabHelper.java` l.74 by: `boolean mDebugLog = true;`
- or adding in `WizPurchase.java` l.359 this line: `mHelper.enableDebugLogging(true);`
